### PR TITLE
Replace useless tid parameters with NULL

### PR DESCRIPTION
**Pull request by zorjen122**

### CODE REVIEW

**Comment by Barenboim** [comment]
At least, on macOS with clang, the function requires a non-null argument:
~~~
test.c:11:36: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
        pthread_create(NULL, NULL, f, NULL);
~~~

**Comment by Barenboim** [comment]
~~~
zsh: segmentation fault  ./a.out
~~~

**Comment by Barenboim** [comment]
But this is legal :)
~~~c
{
    pthread_create(&(pthread_t){0}, NULL, f, NULL);
}
~~~

**Comment by zorjen122** [comment]
> 至少，在带有 clang 的 macOS 上，该函数需要一个非 null 参数：
> 
> ```
> test.c:11:36: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
>         pthread_create(NULL, NULL, f, NULL);
> ```
After consulting posix data, yes, usually the compiler pthread_create implementation will dereference "tid" when attr==NULL. Thanks for your reply.
[posix-pthread_create]“....Upon successful completion, pthread_create() shall store the ID of the created thread in the location referenced by thread.”

**Pull request closed without merging**
