### PR TITLE
[document] Add vcpkg instruction step

### PR DESCRIPTION
**Pull request by JackBoosY**
`workflow` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `workflow` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `workflow`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/workflow/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

### CODE REVIEW

**Comment by Barenboim** [comment]
Thank you. We will merge this PR after our vcpkg package is updated to the latest version.

**Comment by JackBoosY** [comment]
> Thank you. We will merge this PR after our vcpkg package is updated to the latest version.

I have one question:
I've found a distribution mismatch: most don't include `-win`, a few distributions do.
For example, the current latest version is v0.10.3, but there is no corresponding v0.10.3-win.
My question is does the version without `-win` support Windows?

**Comment by Barenboim** [comment]
> > Thank you. We will merge this PR after our vcpkg package is updated to the latest version.
> 
> I have one question: I've found a distribution mismatch: most don't include `-win`, a few distributions do. For example, the current latest version is v0.10.3, but there is no corresponding v0.10.3-win. My question is does the version without `-win` support Windows?

No，the Windows version is a standalone branch. Although having consistent Api, the the master branch does not support Windows platform. We have not enough supporting power for Windows platform, and the Windows version has been lacking of some functions. I am so sorry for that.

**Comment by JackBoosY** [comment]
> No，the Windows version is a standalone branch. Although having consistent Api, the the master branch does not support Windows platform. We have not enough supporting power for Windows platform, and the Windows version has been lacking of some functions. I am so sorry for that.

So for version matching across platforms, we should upgrade to v0.9.11 instead of 0.10.3, right?

**Comment by Barenboim** [comment]
> > No，the Windows version is a standalone branch. Although having consistent Api, the the master branch does not support Windows platform. We have not enough supporting power for Windows platform, and the Windows version has been lacking of some functions. I am so sorry for that.
> 
> So for version matching across platforms, we should upgrade to v0.9.11 instead of 0.10.3, right?

We prefer to upgrade to the latest release for master branch. Version matching is not what we concert indeed. We hope our main line user can install newest package via vckpg. I think we can update Windows branch Version to 0.10.3 too, to meet the policy of consistency.

**Comment by JackBoosY** [comment]
> We prefer to upgrade to the latest release for master branch. Version matching is not what we concert indeed. We hope our main line user can install newest package via vckpg. I think we can update Windows branch Version to 0.10.3 too, to meet the policy of consistency.

Okay, waiting for version 0.10.3-win publish.

**Pull request closed without merging**
