### PR TITLE
WIP: Add tests on Fedora linux

### PR DESCRIPTION
**Pull request by bkmgit**
Related to https://github.com/sogou/workflow/issues/1187

### CODE REVIEW

**Comment by Barenboim** [comment]
Still failed...

**Comment by bkmgit** [comment]
Yes, error is due to `get_filename_component` on newer versions of CMake https://github.com/sogou/workflow/actions/runs/4251285902/jobs/7393433380

**Comment by Barenboim** [comment]
OK, we will fix it. Thanks

**Comment by Barenboim** [comment]
Please reverse this commit: https://github.com/sogou/workflow/pull/1189/commits/182576079c26fa938f288b6e472c169258fbc541

**Comment by Barenboim** [comment]
Could you reopen a pull request? Create a new branch from sogou/workflow master branch and update ci.yml only.

**Comment by Barenboim** [comment]
Because I submitted a wrong commit and mess everything up. Sorry, my fault.

**Comment by Barenboim** [comment]
I think it should be:
get_filename_component(GTEST_PATH ${GTEST_LIBRARY} DIRECTORY ABSOLUTE )

**Comment by Barenboim** [comment]
Passed. By please reopen a PR. We will update CMake.

**Comment by bkmgit** [comment]
Ok, checking Ubuntu as well. Will open a new PR once done. Hopefully, 30 minutes at most.

**Comment by bkmgit** [comment]
Probably order `ABSOLUTE DIRECTORY` vs `DIRECTORY ABSOLUTE` is not important https://cmake.org/cmake/help/latest/command/get_filename_component.html

**Comment by Barenboim** [comment]
Thank you so much!

**Comment by bkmgit** [comment]
Replaced with https://github.com/sogou/workflow/pull/1193

**Pull request closed without merging**
